### ISSUE TITLE
Test--NameError: name 'os' is not defined  Now os module is obviously installed and importable in python

### ISSUE THREAD

**Issue by nnzhangup** [xiezhy6/PASTA-GAN#16]
When i run test.py, the error is as following:
Anyone could run the test.py successfully?

module: <module '_imported_module_65d04ead8c1241548c4d30a4fe7a76b7'>
Loading custom kernel...
Traceback (most recent call last):
  File "/data_superbig/znn/CODE/NIPS2021_PASTA_GAN/PASTA_GAN_main/test.py", line 162, in <module>
    generate_images() # pylint: disable=no-value-for-parameter
  File "/data_superbig/znn/Anaconda3/envs/Try_On37/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/data_superbig/znn/Anaconda3/envs/Try_On37/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/data_superbig/znn/Anaconda3/envs/Try_On37/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data_superbig/znn/Anaconda3/envs/Try_On37/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/data_superbig/znn/Anaconda3/envs/Try_On37/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/data_superbig/znn/CODE/NIPS2021_PASTA_GAN/PASTA_GAN_main/test.py", line 96, in generate_images
    G = legacy.load_network_pkl(f)['G_ema'].to(device) # type: ignore
  File "/data_superbig/znn/CODE/NIPS2021_PASTA_GAN/PASTA_GAN_main/legacy.py", line 21, in load_network_pkl
    data = _LegacyUnpickler(f).load()
  File "/data_superbig/znn/CODE/NIPS2021_PASTA_GAN/PASTA_GAN_main/torch_utils/persistence.py", line 191, in _reconstruct_persistent_obj
    module = _src_to_module(meta.module_src)
  File "/data_superbig/znn/CODE/NIPS2021_PASTA_GAN/PASTA_GAN_main/torch_utils/persistence.py", line 231, in _src_to_module
    exec(src, module.__dict__) # pylint: disable=exec-used
  File "<string>", line 2243, in <module>
NameError: name 'os' is not defined

Process finished with exit code 1

**Comment by stereomatchingkiss** [comment]
In the function _src_to_module, add this line

`src = "import os\n" + src`

**Comment by stereomatchingkiss** [comment]
Better create a new env and install the packages as readme.md mentioned. New packages break old codes
